version: '3'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3002:3002
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - postgres
      - redis
    restart: always
  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"  
    volumes:
      - redis_data:/data  

volumes:
  pgdata:
  redis_data:
